// <auto-generated />
using AdminCore.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AdminCore.Migrations.Migrations
{
    [DbContext(typeof(MigrationsContext))]
    [Migration("20171119234909_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdminCore.BusinessLogic.Products.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_MARCA");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnName("USUARIO_CREADOR");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnName("FECHA_CREACION");

                    b.Property<DateTime>("DateModified")
                        .HasColumnName("FECHA_ACTUALIZACION");

                    b.Property<string>("Description")
                        .HasColumnName("DESCRIPCION")
                        .HasMaxLength(300);

                    b.Property<bool>("IsActive")
                        .HasColumnName("ESTADO_REGISTRO");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnName("USUARIO_MODIFICADOR");

                    b.Property<string>("Name")
                        .HasColumnName("NOMBRE")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("dbo.MARCAS");
                });

            modelBuilder.Entity("AdminCore.BusinessLogic.Products.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NOMBRE")
                        .HasMaxLength(45);

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("dbo.PRODUCTOS");
                });
#pragma warning restore 612, 618
        }
    }
}
